version: "3.7"

services:
  proxy:
    image: "sjoerdvandenbos/proxy:latest"
    networks:
     - our-network
    build:
     context: "./proxy"
    depends_on:
     - stock-service
     - payment-service
     - users-service
     - order-service
    ports:
     - "8080:8080"
    expose:
      - "80"
      - "8080"

  scylla-stock:
  scylla_stock_node1:
    image: scylladb/scylla
    networks:
      - our_network
    command: --seeds=scylla_stock_node1 --smp 1 --overprovisioned 1

  scylla_stock_node2:
    image: scylladb/scylla
    networks:
      - our_network
    command: --seeds=scylla_stock_node1,scylla_stock_node2 --smp 1 --overprovisioned 1

  scylla_stock_node3:
    image: scylladb/scylla
    networks:
      - our-network
    command: "--smp 1 --overprovisioned 1"
    expose:
      - "9042"
  stock-service:
    image: "sjoerdvandenbos/stock_service:scylla"
      - our_network
    command: --seeds=scylla_stock_node1,scylla_stock_node2,scylla_stock_node3 --smp 1 --overprovisioned 1

  stock_service:
    image: "stock_service:latest"
    networks:
      - our-network
    depends_on:
      - scylla-stock
      - scylla_stock_node1
      - scylla_stock_node2
      - scylla_stock_node3
    build:
      context: "./stock_service"
    environment:
      - DB_HOST=scylla-stock
      - DATABASE_TYPE=scylla
    expose:
      - "80"
      - SCYLLA_NODES="scylla_stock_node1 scylla_stock_node2 scylla_stock_node3"

  scylla_users_node1:
    image: scylladb/scylla
    networks:
      - our_network
    command: --seeds=scylla_users_node1 --smp 1 --overprovisioned 1

  scylla-users:
  scylla_users_node2:
    image: scylladb/scylla
    networks:
      - our_network
    command: --seeds=scylla_users_node1,scylla_users_node2 --smp 1 --overprovisioned 1

  scylla_users_node3:
    image: scylladb/scylla
    networks:
     - our-network
    command: "--smp 1 --overprovisioned 1"
    expose:
      - "9042"
  users-service:
    image: "sjoerdvandenbos/users_service:scylla"
      - our_network
    command: --seeds=scylla_users_node1,scylla_users_node2,scylla_users_node3 --smp 1 --overprovisioned 1

  users_service:
    image: "users_service:latest"
    networks:
     - our-network
    depends_on:
     - scylla-users
     - scylla_users_node1
     - scylla_users_node2
     - scylla_users_node3

    build:
      context: "./users_service"
    environment:
      - ORDER_SERVICE_URL=order-service
      - DATABASE_TYPE=scylla
      - DB_HOST=scylla-users
    expose:
      - "80"
      - DB_HOST=scylla_users
      - ORDER_SERVICE=order_service
      - SCYLLA_NODES="scylla_users_node1 scylla_users_node2 scylla_users_node3"

  scylla_payment_node1:
    image: scylladb/scylla
    networks:
      - our_network
    command: --seeds=scylla_payment_node1 --smp 1 --overprovisioned 1

  scylla-payment:
  scylla_payment_node2:
    image: scylladb/scylla
    networks:
      - our_network
    command: --seeds=scylla_payment_node1,scylla_payment_node2 --smp 1 --overprovisioned 1

  scylla_payment_node3:
    image: scylladb/scylla
    networks:
      - our-network
    command: "--smp 1 --overprovisioned 1"
    expose:
      - "9042"
  payment-service:
    image: 'sjoerdvandenbos/payment_service:scylla'
      - our_network
    command: --seeds=scylla_payment_node1,scylla_payment_node2,scylla_payment_node3 --smp 1 --overprovisioned 1

  payment_service:
    image: 'payment_service:latest'
    networks:
      - our-network
    depends_on:
      - scylla-payment
      - scylla_payment_node1
      - scylla_payment_node2
      - scylla_payment_node3
    build:
      context: "./payment_service"
    environment:
      - DB_HOST=scylla-payment
      - DATABASE_TYPE=scylla
      - USER_SERVICE_URL=users-service
    expose:
      - "80"
      - USER_SERVICE_URL=users_service
      - SCYLLA_NODES="scylla_payment_node1 scylla_payment_node2 scylla_payment_node3"

  scylla-order:
  scylla_order_node1:
    image: scylladb/scylla
    networks:
      - our_network
    command: --seeds=scylla_order_node1 --smp 1 --overprovisioned 1

  scylla_order_node2:
    image: scylladb/scylla
    networks:
      - our-network
    command: "--smp 1 --overprovisioned 1"
    expose:
      - "9042"
  order-service:
    image: 'sjoerdvandenbos/order_service:scylla'
      - our_network
    command: --seeds=scylla_order_node1,scylla_order_node2 --smp 1 --overprovisioned 1

  scylla_order_node3:
    image: scylladb/scylla
    networks:
      - our_network
    command: --seeds=scylla_order_node1,scylla_order_node2,scylla_order_node3 --smp 1 --overprovisioned 1

  order_service:
    image: 'order_service:latest'
    networks:
      - our-network
    depends_on:
      - scylla-order
      - scylla_order_node1
      - scylla_order_node2
      - scylla_order_node3
    build:
      context: "./order_service"
    environment:
      - DB_HOST=scylla-order
      - USERS_SERVICE=users-service
      - STOCK_SERVICE=stock-service
      - PAYMENT_SERVICE=payment-service
      - DATABASE_TYPE=scylla
    expose:
      - "80"
      - SCYLLA_NODES="scylla_order_node1 scylla_order_node2 scylla_order_node3"

networks:
  our-network:
    name: our-network
    driver: "bridge"
