version: "3"

services:
  scylla_stock:
    image: scylladb/scylla
    command: "--smp 1 --overprovisioned 1"
  stock_service:
    image: "stock_service:latest"
    depends_on:
      - scylla_stock
    build:
      context: "./stock_service"
    ports:
      - "8000:8000"

  scylla_payment:
    image: scylladb/scylla
    command: "--smp 1 --overprovisioned 1"
  payment_service:
    image: 'payment_service:latest'
    environment:
      - USER_SERVICE_URL=""
    restart: always
    depends_on:
      - scylla_payment
    build:
      context: "./payment_service"
    ports:
    - "5000:5000"
