version: "3.8"

services:
  proxy:
    image: "proxy:latest"
    networks:
     - our_network
    build:
     context: "./proxy"
    depends_on:
     - stock_service
     - payment_service
     - users_service
     - order_service
    ports:
     - "8080:8080"

  scylla_stock_node1:
    image: scylladb/scylla
    networks:
      - our_network
    command: --seeds=scylla_stock_node1 --smp 1 --overprovisioned 1

  scylla_stock_node2:
    image: scylladb/scylla
    networks:
      - our_network
    command: --seeds=scylla_stock_node1,scylla_stock_node2 --smp 1 --overprovisioned 1

  scylla_stock_node3:
    image: scylladb/scylla
    networks:
      - our_network
    command: --seeds=scylla_stock_node1,scylla_stock_node2,scylla_stock_node3 --smp 1 --overprovisioned 1

  stock_service:
    image: "stock_service:latest"
    networks:
      - our_network
    depends_on:
      - scylla_stock_node1
      - scylla_stock_node2
      - scylla_stock_node3
    build:
      context: "./stock_service"
    environment:
      - DB_HOST=scylla_stock
      - DATABASE_TYPE=scylla
      - SCYLLA_NODES="scylla_stock_node1 scylla_stock_node2 scylla_stock_node3"

  scylla_users:
    image: scylladb/scylla
    networks:
     - our_network
    command: "--smp 1 --overprovisioned 1"

  users_service:
    image: "users_service:latest"
    networks:
     - our_network
    depends_on:
     - scylla_users
    build:
      context: "./users_service"
    environment:
      - DATABASE_TYPE=scylla
      - DB_HOST=scylla_users
      - ORDER_SERVICE=order_service

  scylla_payment:
    image: scylladb/scylla
    networks:
      - our_network
    command: "--smp 1 --overprovisioned 1"

  payment_service:
    image: 'payment_service:latest'
    networks:
      - our_network
    depends_on:
      - scylla_payment
    build:
      context: "./payment_service"
    environment:
      - DB_HOST=scylla_payment
      - USER_SERVICE_URL=users_service

  scylla_order:
    image: scylladb/scylla
    networks:
      - our_network
    command: "--smp 1 --overprovisioned 1"

  order_service:
    image: 'order_service:latest'
    networks:
      - our_network
    depends_on:
      - scylla_order
    build:
      context: "./order_service"
    environment:
      - DB_HOST=scylla_order
      - USERS_SERVICE=users_service
      - STOCK_SERVICE=stock_service
      - PAYMENT_SERVICE=payment_service
      - DATABASE_TYPE=scylla

networks:
  our_network:
    driver: "bridge"
    name: our_network

