version: "3.8"

services:
  proxy:
    image: "proxy:latest"
    networks:
     - our_network
    build:
     context: "./proxy"
    depends_on:
     - stock_service
     - payment_service
     - users_service
     - order_service
    ports:
     - "8080:8080"

  stock_service:
    image: "stock_service:latest"
    networks:
      - our_network
    depends_on:
      - postgres
    build:
      context: "./stock_service"
    environment:
      - DB_HOST=postgres
      - DATABASE_TYPE=postgres
      - POSTGRES_PASSWORD=notsosecret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432

  users_service:
    image: "users_service:latest"
    networks:
     - our_network
    depends_on:
     - postgres
    build:
      context: "./users_service"
    environment:
      - DATABASE_TYPE=postgres
      - DB_HOST=postgres
      - POSTGRES_PASSWORD=notsosecret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - ORDER_SERVICE_URL=order_service

  payment_service:
    image: 'payment_service:latest'
    networks:
      - our_network
    depends_on:
      - postgres
    build:
      context: "./payment_service"
    environment:
      - DB_HOST=postgres
      - USER_SERVICE_URL=users_service
      - DATABASE_TYPE=postgres
      - POSTGRES_PASSWORD=notsosecret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432

  order_service:
    image: 'order_service:latest'
    networks:
      - our_network
    depends_on:
      - postgres
    build:
      context: "./order_service"
    environment:
      - DB_HOST=postgres
      - DATABASE_TYPE=postgres
      - USERS_SERVICE=users_service
      - STOCK_SERVICE=stock_service
      - PAYMENT_SERVICE=payment_service
      - POSTGRES_PASSWORD=notsosecret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432

  postgres:
    image: "postgres"
    networks:
      - our_network
    environment:
      - POSTGRES_PASSWORD=notsosecret

networks:
  our_network:
    driver: "bridge"
    name: our_network
