version: "3.8"

services:
  proxy:
    image: "proxy:latest"
    networks:
     - our_network
    build:
     context: "./proxy"
    depends_on:
     - stock_service
     - payment_service
     - users_service
     - order_service
    ports:
     - "8080:8080"

  scylla_stock:
    image: scylladb/scylla
    networks:
      - our_network
    command: "--smp 1 --overprovisioned 1"
  stock_service:
    image: "stock_service:latest"
    networks:
      - our_network
    depends_on:
      - scylla_stock
    build:
      context: "./stock_service"

  scylla_users:
    image: scylladb/scylla
    networks:
     - our_network
    command: "--smp 1 --overprovisioned 1"
  users_service:
    image: "users_service:latest"
    networks:
     - our_network
    depends_on:
     - scylla_users
    build:
      context: "./users_service"

  scylla_payment:
    image: scylladb/scylla
    networks:
      - our_network
    command: "--smp 1 --overprovisioned 1"
  payment_service:
    image: 'payment_service:latest'
    networks:
      - our_network
    depends_on:
      - scylla_payment
    build:
      context: "./payment_service"

  scylla_order:
    image: scylladb/scylla
    networks:
      - our_network
    command: "--smp 1 --overprovisioned 1"
  order_service:
    image: 'order_service:latest'
    networks:
      - our_network
    depends_on:
      - scylla_order
    build:
      context: "./order_service"

networks:
  our_network:
    driver: "bridge"
    name: our_network

