version: "3.8"

services:
  proxy:
    image: "sjoerdvandenbos/proxy:latest"
    networks:
     - our_network
    build:
     context: "./proxy"
    depends_on:
     - stock-service
     - payment-service
     - users-service
     - order-service
    ports:
     - "8080:8080"

  stock-service:
    image: "sjoerdvandenbos/stock_service:latest"
    networks:
      - our_network
    depends_on:
      - postgres
    build:
      context: "./stock_service"
    environment:
      - DB_HOST=postgres
      - DATABASE_TYPE=postgres
      - POSTGRES_PASSWORD=notsosecret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432

  users-service:
    image: "sjoerdvandenbos/users_service:latest"
    networks:
     - our_network
    depends_on:
     - postgres
    build:
      context: "./users_service"
    environment:
      - DATABASE_TYPE=postgres
      - DB_HOST=postgres
      - POSTGRES_PASSWORD=notsosecret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - ORDER_SERVICE_URL=order-service

  payment-service:
    image: 'sjoerdvandenbos/payment_service:latest'
    networks:
      - our_network
    depends_on:
      - postgres
    build:
      context: "./payment_service"
    environment:
      - DB_HOST=postgres
      - USER_SERVICE_URL=users-service
      - DATABASE_TYPE=postgres
      - POSTGRES_PASSWORD=notsosecret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432

  order-service:
    image: 'sjoerdvandenbos/order_service:latest'
    networks:
      - our_network
    depends_on:
      - postgres
    build:
      context: "./order_service"
    environment:
      - DB_HOST=postgres
      - DATABASE_TYPE=postgres
      - USERS_SERVICE=users-service
      - STOCK_SERVICE=stock-service
      - PAYMENT_SERVICE=payment-service
      - POSTGRES_PASSWORD=notsosecret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432

  postgres:
    image: "postgres"
    networks:
      - our_network
    environment:
      - POSTGRES_PASSWORD=notsosecret

networks:
  our_network:
    driver: "bridge"
    name: our_network
