version: "3.7"

services:
  proxy:
    image: "sjoerdvandenbos/proxy:latest"
    networks:
     - our-network
    build:
     context: "./proxy"
    depends_on:
     - stock-service
     - payment-service
     - users-service
     - order-service
    ports:
     - "8080:8080"
    expose:
      - "8080"

  scylla-stock-node1:
    image: scylladb/scylla
    networks:
      - our-network
    command: --seeds=scylla-stock-node1 --smp 1 --overprovisioned 1
    expose:
      - "7000"
      - "7001"
      - "7199"
      - "9042"

  scylla-stock-node2:
    image: scylladb/scylla
    networks:
      - our-network
    command: --seeds=scylla-stock-node1,scylla-stock-node2 --smp 1 --overprovisioned 1
    expose:
      - "7000"
      - "7001"
      - "7199"
      - "9042"

  scylla-stock-node3:
    image: scylladb/scylla
    networks:
      - our-network
    command: --seeds=scylla-stock-node1,scylla-stock-node2,scylla-stock-node3 --smp 1 --overprovisioned 1
    expose:
      - "7000"
      - "7001"
      - "7199"
      - "9042"

  stock-service:
    image: "sjoerdvandenbos/stock_service:scylla"
    networks:
      - our-network
    depends_on:
      - scylla-stock-node1
      - scylla-stock-node2
      - scylla-stock-node3
    build:
      context: "./stock_service"
    environment:
      - DB_HOST=scylla-stock
      - DATABASE_TYPE=scylla
      - SCYLLA_NODES="scylla-stock-node1 scylla-stock-node2 scylla-stock-node3"
    expose:
      - "80"

  scylla-users-node1:
    image: scylladb/scylla
    networks:
      - our-network
    command: --seeds=scylla-users-node1 --smp 1 --overprovisioned 1
    expose:
      - "7000"
      - "7001"
      - "7199"
      - "9042"

  scylla-users-node2:
    image: scylladb/scylla
    networks:
      - our-network
    command: --seeds=scylla-users-node1,scylla-users-node2 --smp 1 --overprovisioned 1
    expose:
      - "7000"
      - "7001"
      - "7199"
      - "9042"

  scylla-users-node3:
    image: scylladb/scylla
    networks:
     - our-network
    command: --seeds=scylla-users-node1,scylla-users-node2,scylla-users-node3 --smp 1 --overprovisioned 1
    expose:
      - "7000"
      - "7001"
      - "7199"
      - "9042"

  users-service:
    image: "sjoerdvandenbos/users_service:scylla"
    networks:
     - our-network
    depends_on:
     - scylla-users-node1
     - scylla-users-node2
     - scylla-users-node3
    build:
      context: "./users_service"
    environment:
      - ORDER_SERVICE_URL=order-service
      - DATABASE_TYPE=scylla
      - DB_HOST=scylla-users
      - ORDER_SERVICE=order-service
      - SCYLLA_NODES="scylla-users-node1 scylla-users-node2 scylla-users-node3"
    expose:
      - "80"

  scylla-payment-node1:
    image: scylladb/scylla
    networks:
      - our-network
    command: --seeds=scylla-payment-node1 --smp 1 --overprovisioned 1
    expose:
      - "7000"
      - "7001"
      - "7199"
      - "9042"

  scylla-payment-node2:
    image: scylladb/scylla
    networks:
      - our-network
    command: --seeds=scylla-payment-node1,scylla-payment-node2 --smp 1 --overprovisioned 1
    expose:
      - "7000"
      - "7001"
      - "7199"
      - "9042"

  scylla-payment-node3:
    image: scylladb/scylla
    networks:
      - our-network
    command: --seeds=scylla-payment-node1,scylla-payment-node2,scylla-payment-node3 --smp 1 --overprovisioned 1
    expose:
      - "7000"
      - "7001"
      - "7199"
      - "9042"

  payment-service:
    image: 'sjoerdvandenbos/payment_service:scylla'
    networks:
      - our-network
    depends_on:
      - scylla-payment-node1
      - scylla-payment-node2
      - scylla-payment-node3
    build:
      context: "./payment_service"
    environment:
      - DB_HOST=scylla-payment
      - DATABASE_TYPE=scylla
      - USER_SERVICE_URL=users-service
      - SCYLLA_NODES="scylla-payment-node1 scylla-payment-node2 scylla-payment-node3"
    expose:
      - "80"

  scylla-order-node1:
    image: scylladb/scylla
    networks:
      - our-network
    command: --seeds=scylla-order-node1 --smp 1 --overprovisioned 1
    expose:
      - "7000"
      - "7001"
      - "7199"
      - "9042"

  scylla-order-node2:
    image: scylladb/scylla
    networks:
      - our-network
    command: --seeds=scylla-order-node1,scylla-order-node2 --smp 1 --overprovisioned 1
    expose:
      - "7000"
      - "7001"
      - "7199"
      - "9042"

  scylla-order-node3:
    image: scylladb/scylla
    networks:
      - our-network
    command: --seeds=scylla-order-node1,scylla-order-node2,scylla-order-node3 --smp 1 --overprovisioned 1
    expose:
      - "7000"
      - "7001"
      - "7199"
      - "9042"

  order-service:
    image: 'sjoerdvandenbos/order_service:scylla'
    networks:
      - our-network
    depends_on:
      - scylla-order-node1
      - scylla-order-node2
      - scylla-order-node3
    build:
      context: "./order_service"
    environment:
      - DB_HOST=scylla-order
      - USERS_SERVICE=users-service
      - STOCK_SERVICE=stock-service
      - PAYMENT_SERVICE=payment-service
      - DATABASE_TYPE=scylla
      - SCYLLA_NODES="scylla-order-node1 scylla-order-node2 scylla-order-node3"
    expose:
      - "80"

networks:
  our-network:
    name: our-network
    driver: "bridge"
