apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out scylla_deployment
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: order-service
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: order-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out scylla_deployment
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/our-network: "true"
        io.kompose.service: order-service
    spec:
      containers:
      - env:
        - name: DATABASE_TYPE
          value: scylla
        - name: DB_HOST
          value: scylla-order
        - name: PAYMENT_SERVICE
          value: payment-service
        - name: STOCK_SERVICE
          value: stock-service
        - name: USERS_SERVICE
          value: users-service
        image: sjoerdvandenbos/order_service:scylla
        imagePullPolicy: ""
        name: order-service
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
