apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --out scylla_deployment
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: payment-service
  name: payment-service
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    io.kompose.service: payment-service
status:
  loadBalancer: {}
