apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out scylla_deployment
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: scylla-order-node3
  name: scylla-order-node3
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: scylla-order-node3
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out scylla_deployment
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/our-network: "true"
        io.kompose.service: scylla-order-node3
    spec:
      containers:
      - args: ["--seeds", "scylla-order-node1,scylla-order-node2,scylla-order-node3", "--smp", "1", "--overprovisioned", "1"]
        image: scylladb/scylla
        imagePullPolicy: ""
        name: scylla-order-node3
        ports:
        - containerPort: 7000
        - containerPort: 7001
        - containerPort: 7199
        - containerPort: 9042
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
