apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --out scylla_deployment
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: scylla-payment
  name: scylla-payment
spec:
  ports:
  - name: "9042"
    port: 9042
    targetPort: 9042
  selector:
    io.kompose.service: scylla-payment
status:
  loadBalancer: {}
