apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out scylla_deployment
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: stock-service
  name: stock-service
spec:
  replicas: 10
  selector:
    matchLabels:
      io.kompose.service: stock-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out scylla_deployment
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: stock-service
    spec:
      containers:
      - env:
        - name: DATABASE_TYPE
          value: scylla
        - name: DB_HOST
          value: scylla
        - name: SCYLLA_NODES
          value: "scylla"
        image: sjoerdvandenbos/stock_service:scylla
        imagePullPolicy: Always
        name: stock-service
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
