apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out scylla_deployment
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: users-service
  name: users-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: users-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out scylla_deployment
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/our-network: "true"
        io.kompose.service: users-service
    spec:
      containers:
      - env:
        - name: DATABASE_TYPE
          value: scylla
        - name: DB_HOST
          value: scylla-users
        - name: ORDER_SERVICE_URL
          value: order-service
        image: sjoerdvandenbos/users_service:scylla
        imagePullPolicy: ""
        name: users-service
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
