apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  namespace: postgres-space
  name: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        envFrom:
        - configMapRef:
            name: postgres-config
        ports:
        - containerPort: 5432
          name: postgres
#        volumeMounts:
#        - name: postgresdb
#          mountPath: /var/lib/postgresql/data
#          subPath: postgres
#  volumeClaimTemplates:
#  - metadata:
#      name: postgresdb
#      labels:
#        app: postgres-data
#    spec:
#      accessModes: ["ReadWriteOnce"]
#      resources:
#        requests:
#          storage: 100Gi
