apiVersion: v1
kind: Service
metadata:
  namespace: postgres-space
  labels:
    name: proxy
  name: proxy
spec:
  type: LoadBalancer
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    name: proxy
