apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: postgres-space
  labels:
    name: users-service
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    name: users-service
